set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
set number
set tabstop=4
set shiftwidth=4
set expandtab
set cursorline
set colorcolumn=80
set exrc
set secure
color slate


" Tab Plugin Settings
"let g:indentLine_char = '|'
"let g:indentLine_color_term = 42
"hi Folded ctermbg=darkgrey
"hi clear SpellBad
"hi SpellBad cterm=undercurl
"hi Search ctermbg=black ctermfg=yellow cterm=underline
"set ssop-=options
"set ssop-=folds
"let glib_deprecated_errors = 1

"Fold method
set foldmethod=indent
set foldlevel=0
set foldnestmax=1
let c_no_comment_fold = 1

" Remaps
nnoremap <silent><Leader><C-]> <C-w><C-]><C-w>T " Remap openning function definition on new tab
nnoremap th  :tabfirst<CR>
nnoremap tj  :tabnext<CR>
nnoremap tk  :tabprev<CR>
nnoremap tl  :tablast<CR>
nnoremap tt  :tabedit<Space>
nnoremap tn  :tabnext<Space>
nnoremap tm  :tabm<Space>
nnoremap td  :tabclose<CR>
